name: Expression request
description: Suggest idea for this project
labels: ["enhancement"]
body:
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Check existing issues
      description: If someone has already opened an issue for what you are requesting, please add a 👍 reaction to the existing issue instead of creating a new one.
      options:
         - label: I have [checked for existing issues](https://github.com/Esri/arcade-expressions/issues) to avoid duplicates.
    validations:
      required: true
  - type: dropdown
    id: execution-profile
    validations:
      required: true
    attributes:
      label: Execution profile
      multiple: false
      description: Environment controlling the expression's execution (more about [Arcade Profiles](https://developers.arcgis.com/arcade/profiles/))
      options:
        - Any
        - Alias
        - Calculation
        - Constraint
        - Dashboard data
        - Form Calculation
        - Labeling
        - Popup
        - Visualization
        - I don't know
  - type: textarea
    id: expression-request
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, layers, webmaps, code, about the feature request here.
    validations:
      required: false